### ISSUE TITLE
Can I enlarge the resolution from 32*32 to ...?

### ISSUE THREAD

**Issue by 013292** [google-research/nerf-from-image#15]
Thanks for sharing this work.
May I ask the right or elegant way to enlarge the resolution. The default is 32*32 right?
Does it have any negative effect if I enlarge the resolution?
Why do you choose the 32 * 32 in both this work and Pix2NeRF?
Appreciate :-)

**Comment by dariopavllo** [comment]
Hi,

The default resolution is 128x128. I believe Pix2NeRF (who has been written by different authors) is trained at a lower resolution (64x64).

The choice of the resolution is mostly a matter of computational cost / available GPU memory, as well as stability during training. For some datasets (e.g. ShapeNet), 128x128 is the native resolution of the dataset. You might be able to increase the resolution, but most likely you also need to increase the strength of the R1 regularization to improve stability.
