### ISSUE TITLE
Qualitative results produced on ImageNet

### ISSUE THREAD

**Issue by AleksErsh** [google-research/nerf-from-image#4]
Using your code and pretrained on ImageNet models I produced the results for ImageNet classes.
I observed qualitative results that differ from those mentioned in the article with the exception of cars. What confuses me most of all is that the results for cars are much better than for other classes.
Please advise if these results are expected or if they are very different in quality from those you received. Thank you in advance. 
  
![Cars](https://user-images.githubusercontent.com/94178827/218755135-5d0c3898-822d-4570-8fc1-ef5309cea1f1.png)
![Airplanes](https://user-images.githubusercontent.com/94178827/218764229-d7be0d81-a3d9-446e-bd18-deafcea89b3b.png)
![Motorcycles](https://user-images.githubusercontent.com/94178827/218764299-828b21c0-60ce-4b6c-b21c-f0c557ab9e96.png)
![Elephant](https://user-images.githubusercontent.com/94178827/218764347-b253b8ab-fc8d-4bf5-86d5-2c7264649e91.png)
![Zebra](https://user-images.githubusercontent.com/94178827/218764395-ab2b4e37-661f-48c8-b37a-47f76b103093.png)

**Comment by dariopavllo** [comment]
Hi,

I think there is something wrong going on (I notice issues with pose estimation, cropping, and color saturation).

Can you make sure of the following?
- The encoder requires images in the [-1, 1] range at 128x128. The background should have a value of 0, which should appear as gray in the rendered images. The fact that your images have a black background makes me think that you either assigned a value of -1 or are using a wrong range [0, 1].
- The images should be rendered using estimated poses, with no bounding box inputs to the renderer. On cars the pose estimation should be almost perfect, without the obvious cropping difference that I can see in the last car image.
- For debugging purposes, I suggest that you first visualize the results from the encoder, without the inversion step. They should already look quite right.

Anyway, we plan to release a reference implementation soon.
